name: NestJs CICD Development

on:
  push:
    branches:
      - development
#      - test
#      - staging
#      - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: build_script=build_${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}
          
      - name: Save DigitalOcean kubeconfig
        run: doctl -t ${{ secrets.DOCTL_TOKEN }} k8s cluster kubeconfig show ${{ vars.K8S_CLUSTER }} > kubeconfig.yml

      - name: Restart deployments
        run: kubectl --insecure-skip-tls-verify --kubeconfig=kubeconfig.yml rollout restart deployment/easy-2-drop-api --namespace=${{ vars.NAMESPACE_PREFIX }}-${{ github.ref_name }}
